name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing ssh connection
        uses: apleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.GOFRI_SECRET }}
          port: 22
          script: |
            cd projects/gofri
            git pull
            npm i
            npm run build
            pm2 restart Gofri
